### ISSUE TITLE
Impossibilité de chercher dans un champ JSON si celui-ci contient un tableau

### ISSUE THREAD

**Issue by KuiKui** [Innmind/Doctrine#1]
## Quoi

Si le JSON stocké en DB est composé d'une seule valeur : `"première valeur"` ou `123`, tout fonctionne comme attendu.

Par contre, si le JSON stocké en DB est composé d'un tableau : `["081be0b6-eda8", "a7eeafd8-35d9"]`, alors aucune correspondance n'est trouvée.

## Pourquoi

C'est probablement en rapport avec le comportement de la fonction `json_value` qui ne peut remonter des valeurs d'un tableau que si elle sont indexées :

```
MariaDB [mgx]> select json_value('["081be0b6-eda8", "a7eeafd8-35d9"]', '$');
+-------------------------------------------------------+
| json_value('["081be0b6-eda8", "a7eeafd8-35d9"]', '$') |
+-------------------------------------------------------+
| NULL                                                  |
+-------------------------------------------------------+
1 row in set (0.000 sec)

MariaDB [mgx]> select json_value('["081be0b6-eda8", "a7eeafd8-35d9"]', '$[0]');
+----------------------------------------------------------+
| json_value('["081be0b6-eda8", "a7eeafd8-35d9"]', '$[0]') |
+----------------------------------------------------------+
| 081be0b6-eda8                                            |
+----------------------------------------------------------+
1 row in set (0.000 sec)
```

## Comment

Peut-être regarder du coté de la fonction `json_search`, qui permet d'obtenir l'index à utiliser dans la fonction `json_value` :

```
MariaDB [mgx]> select json_search('["081be0b6-eda8", "a7eeafd8-35d9"]', 'one', 'a7eeafd8-35d9');
+---------------------------------------------------------------------------+
| json_search('["081be0b6-eda8", "a7eeafd8-35d9"]', 'one', 'a7eeafd8-35d9') |
+---------------------------------------------------------------------------+
| "$[1]"                                                                    |
+---------------------------------------------------------------------------+
1 row in set (0.000 sec)
```

Peut-être est-il possible de les imbriquer (j'ai essayé la version simple, mais cela ne semble pas fonctionner) ?

**Comment by Baptouuuu** [comment]
En version `1.5.0` une nouvelle spécification (`Innmind\Doctrine\Specification\JsonArray`) a été ajoutée qui permet de faire une recherche dans un tableau. La librairie ne peut pas détecter automatiquement le format de la valeur stockée en base pour faire ça automatiquement donc il faut modifier le code pour utiliser `JsonArray::contains('property', 'value')`.
